export const mockData: ITreeData = {
  id: null,
  code: "vtwo_menu_root_v11",
  name: "侧边栏菜单页面",
  cn: 0,
  sn: 0,
  tn: 0,
  ext: { DT: "1", OP: "1", RT: "menu", IB: "0" },
  items: [
    {
      id: null,
      code: "vtwo_menu_21820_v11",
      name: "核心指标",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_main_v11",
          name: "单车首页",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_21920_v11",
          name: "App日报",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21830_v11",
      name: "单车",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_21930_v11",
          name: "实时监控",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22320_v11",
              name: "实时核心指标监控",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22330_v11",
              name: "实时移动端访问量",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_21940_v11",
          name: "全局分析",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22350_v11",
              name: "全局分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22360_v11",
              name: "全局分析周报",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_22890_v11",
                  name: "全局分析周报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_22900_v11",
                  name: "全局分析周报-城市排名",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22370_v11",
              name: "长征",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_22910_v11",
                  name: "长征项目数据报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_bikePerformance_v11",
          name: "绩效看板",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_21950_v11",
          name: "资产状态",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22380_v11",
              name: "资产健康",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22390_v11",
              name: "日报",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_21960_v11",
          name: "库外运营",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22410_v11",
              name: "运营日报",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_22930_v11",
                  name: "运营日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_22940_v11",
                  name: "校园日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_22950_v11",
                  name: "单车日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22420_v11",
              name: "运力管理",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_22970_v11",
                  name: "干预核心指标",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_22980_v11",
                  name: "干预围栏",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_22990_v11",
                  name: "干预反作弊",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22430_v11",
              name: "运力效率",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23000_v11",
                  name: "车辆调度",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23010_v11",
                  name: "调度收益v4",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23020_v11",
                  name: "兼职日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23030_v11",
                  name: "调度实验",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22440_v11",
              name: "运营武器",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtow_menu_223042_v11",
                  name: "997点位看板",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23105_v11",
                  name: "运营效率",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23040_v11",
                  name: "运营全链路时效",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23050_v11",
                  name: "网格化报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23060_v11",
                  name: "围栏工具",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23070_v11",
                  name: "B端宽表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtow_menu_23085_v11",
                  name: "政府扣车",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23080_v11",
                  name: "故障车导出工具v5",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23090_v11",
                  name: "异常移动资产监控",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23100_v11",
                  name: "私占报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_bikeLocation_sedimentation_v11",
                  name: "淤积车辆查询",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_bikeLocation_nearby_v11",
                  name: "附近车辆查询",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_bikeVast_v11",
                  name: "车辆位置分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_21970_v11",
          name: "库内管理",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22450_v11",
              name: "库内维修",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23140_v11",
                  name: "维修效率",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23160_v11",
                  name: "维修人效",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23150_v11",
                  name: "维修质量",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23170_v11",
                  name: "仓库备件配备情况",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23200_v11",
                  name: "自管维修师结费数据",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22460_v11",
              name: "车质量",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23210_v11",
                  name: "零配件追溯报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_21980_v11",
          name: "用户增长",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22480_v11",
              name: "新注册用户转化日报",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22490_v11",
              name: "骑行用户留存",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22500_v11",
              name: "应用统计分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22510_v11",
              name: "订单分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23220_v11",
                  name: "骑行用户核心指标",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23230_v11",
                  name: "订单分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22520_v11",
              name: "资源位流量",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_21990_v11",
          name: "用户体验",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22530_v11",
              name: "开锁体验",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_dataGraph_scanStateV2_v11",
                  name: "扫码转化漏斗",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22540_v11",
              name: "关锁结费",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23290_v11",
                  name: "关锁成功率",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_dataGraph_ReturnChargeState_v11",
                  name: "异常结费报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_22000_v11",
          name: "收入套餐",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_22560_v11",
              name: "单车收入",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22570_v11",
              name: "骑行套餐",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23320_v11",
                  name: "月卡核心指标",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_22590_v11",
              name: "套餐复购",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_22600_v11",
              name: "定价策略",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_23350_v11",
                  name: "单车月次卡定价",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_23360_v11",
                  name: "单车定价及补贴",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21840_v11",
      name: "电单车",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "cd4061a8-d1f5-4135-b020-2946a43b620c_v11",
          name: "全局决策",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "0c3787fe-06ae-4cd2-a4f2-9cdf559dcec2_v11",
              name: "电单车日报",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "4f6029be-49c9-40fa-8420-a0050882c471_v11",
              name: "全局分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "703926c3-8eae-4c19-a236-40fcfeb5b933_v11",
              name: "财务分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "2f9c0b98-13fd-497b-a63e-a46e170f9c6f_v11",
                  name: "电单车收入",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_performance_v11",
          name: "绩效看板",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "7b9a0a26-cdce-43ce-95c1-7b58055883d4_v11",
          name: "作战地图",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "ed8606a2-4afe-423c-964f-187cb030e562_v11",
              name: "管理看板",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_cityExpand_v11",
              name: "开城拓展",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_expandMap_v11",
                  name: "拓展地图",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_cityProcessReport_v11",
                  name: "开城流程报表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "4620432d-dcdf-4d21-a987-390b4cdb718e_v11",
          name: "实时大盘",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "3cbbf1ac-94c0-45f2-9984-1309b6ad1401_v11",
              name: "订单实况",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "3eae9b7f-58f0-4669-88fb-50a41ce49ede_v11",
                  name: "实时订单",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "7080bd83-144a-4b63-890c-331dfb8688fd_v11",
                  name: "实时订单_分车型",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "c3c769f2-d466-43be-80d7-cd445a14b7b2_v11",
              name: "车辆实况",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_bikeLocation_park_v11",
                  name: "停车点车辆数",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_bikeLocation_nearbyBattery_v11",
                  name: "附近车辆查询",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_bikeVastBattery_v11",
                  name: "车辆位置分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "8904782a-b390-4ac5-a74e-874d31ff3667_v11",
                  name: "异常移动",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "9a8af1ad-251c-493a-b103-e5786ddad8f7_v11",
              name: "围栏实况",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_bikeLocation_exchange_v11",
                  name: "围栏低电占比",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "a8e84095-04f3-4e33-bc12-25815ab5bc58_v11",
          name: "增长体验",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "93e5d401-4ebc-4dba-8f97-48e6cc83e6b1_v11",
              name: "用户增长",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "1e420f13-e138-4884-b884-cb244ddd5b42_v11",
                  name: "用户增长核心指标",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "d9350480-be8a-47c2-aacc-7bc4f88b4552_v11",
                  name: "用户留存",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "e7c0d23e-97de-430f-bf16-7382f0672b36_v11",
                  name: "用户流转",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "846d3514-0433-4450-8d99-12eebeee95de_v11",
              name: "用户体验",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "aa52b106-2f6a-44b5-9f89-dede3cb331f6_v11",
                  name: "C端产品体验",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "b59ea3d1-458d-40cf-88a7-c397e3ada3a5_v11",
                  name: "体验漏斗",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "ebc56ad5-9a3e-4f5f-9b16-5660f960c355_v11",
                  name: "扫码低电",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "c0b16cc1-8bc5-4b8c-8b5e-c055ba30517a_v11",
              name: "骑行套餐",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "6034bc8d-67f1-4b85-a721-fe5e7386d993_v11",
                  name: "骑行券分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "6269f828-02dc-4cdf-82a4-72e78abc1940_v11",
                  name: "月卡分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "8fd96f91-8301-4a30-9aec-18e2526d3498_v11",
                  name: "次卡分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "d43346ae-f06b-44a4-9091-76c55e9c7e9e_v11",
                  name: "套餐复购",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "7ac10f09-71b2-4415-8912-d00c5cc3adc2_v11",
              name: "价格诊断",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "32040dbb-d3e4-40fb-a9bc-765599bbee83_v11",
                  name: "定价策略",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "34ac79df-81e3-418e-ac14-159ce984ee24_v11",
          name: "资产健康",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "bdd0c205-0cd0-428e-ab71-a90261b2a910_v11",
              name: "电单车",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "a6469ef7-48ae-4d0a-8451-ea9bf160e622_v11",
                  name: "状态树",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "b57f4c40-abed-481d-a32b-897cd20e91d4_v11",
                  name: "资产健康分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "be9ffa56-9a25-47a1-bb79-cb008528a8a4_v11",
                  name: "资产健康_分车型",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "2e846c7b-58f4-4dea-8498-525de7f05142_v11",
                  name: "故障分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_lost_state_v11",
                  name: "丢失态",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "0198bb63-d131-4496-8827-f638f3b963d6_v11",
              name: "电池",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "71d64e28-99fd-4cf8-86b1-60acbf549d56_v11",
                  name: "状态树",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "257e5b8b-c944-4f46-b118-1fb1839491d7_v11",
                  name: "资产健康分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_page_dianchipandian",
                  name: "电池盘点",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "page", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_battery_status_detail_v11",
                  name: "电池状态明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "vtwo_menu_l3_kouche",
              name: "扣车分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_L4_koucheribao",
                  name: "扣车日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_l4_kouchemingxi",
                  name: "扣车明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_l4_koucheweilandangan",
                  name: "扣车围栏档案",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "aea2d696-e2c7-445c-94c0-1368efe4047d_v11",
          name: "库内管理",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "d3323e04-980b-40dd-8c46-7785e6cacb03_v11",
              name: "库内维修",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "1a90c6f6-4cf9-495b-809f-86351b36dd94_v11",
                  name: "维修日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "13099bb3-34c6-42f5-ab52-78f0ded8409c_v11",
                  name: "维修明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "d8a5130c-ffc4-4c41-bd3a-0ef032b0a0e9_v11",
              name: "出入库",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "9cac8a46-f8c4-4c52-ae67-1d7a885b72f4_v11",
                  name: "电单车",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "56c489de-24c6-49c8-92ac-37174e15e0f5_v11",
                  name: "电池",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_page_dianchishishichuruku",
                  name: "电池实时出入库",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "page", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "93d350e2-5185-41b2-b651-757c22703220_v11",
          name: "库外运营",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "f1cb689f-99ba-4bc4-8741-e6c9478fe390_v11",
              name: "换电",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "5666b06d-c97d-4746-abc6-027d3f6793d5_v11",
                  name: "换电周报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "2d1f6368-7fa3-4634-bbe8-720ead71feb0_v11",
                  name: "换电日报",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "f6438fe5-1dd1-4dfc-a51d-de3a2584aa29_v11",
                  name: "换电人效与商管理",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "797938b1-4e0a-43c3-9dd2-94145aa802e3_v11",
                  name: "城市换电工具",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "12806501-a4d8-4421-8f49-f38d0ceab294_v11",
                  name: "城市换电分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "f375618c-6d0e-481c-b5e8-4311178c6b24_v11",
                  name: "运营专员换电明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "80f5f9ad-f8f8-462b-8b88-32d14fb69019_v11",
                  name: "平均骑行里程",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "d57fcfbe-eaac-49d6-aa4a-3b756e6e3468_v11",
                  name: "换电（旧看板）",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "7696ce11-648f-4c0d-81d3-b97598ca99ef_v11",
              name: "调度",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "a5b51f1b-1973-4206-955e-a9c816f64b23_v11",
                  name: "调度宽表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "5ef7fec6-cd4d-49a8-8271-4a4e592c8a1f_v11",
                  name: "调度明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "30c2a7e0-cb3c-49ba-89ea-306f3ee0fe9d_v11",
                  name: "调出点策略",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "b7e7ea4a-190a-4553-ad62-da0ba328f1f1_v11",
              name: "干预",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "d572f513-48d1-4519-9649-e63fa91fecdc_v11",
                  name: "干预量",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "2211c8c4-b353-4c48-b8ba-84bb731c1f55_v11",
                  name: "干预明细",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "de4fe4b8-7a99-47fc-bb00-ad506ebf962f_v11",
                  name: "干预宽表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "c33200bb-dbdd-46a2-9e92-4158114c68c1_v11",
              name: "寻回",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "8f910a5c-71f0-4a2e-8af7-f5234d74b847_v11",
                  name: "装车",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "5fc5fee3-190d-44d4-aaef-cbdacff25a9a_v11",
                  name: "卸车",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "7e222ecc-36a0-4e93-8011-a76b00bca1bd_v11",
          name: "供需匹配",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_grid_ops_v11",
              name: "网格化运营",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_grid_manage_v11",
                  name: "电单车网格化管理指标宽表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_street_manage_v11",
                  name: "电单车运营街道管理指标宽表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "f03f24b6-3bd3-4df6-8f40-6646754685f9_v11",
              name: "时空围栏",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "d8b33109-ad2f-486e-8a3e-e43285400f59_v11",
                  name: "围栏网格取数",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_l4_hexinweilankanban",
                  name: "核心围栏看板",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_ops_board_v11",
                  name: "运营围栏看板",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "8b53329b-1556-467b-a3f0-8c4900e0eda9_v11",
              name: "车辆供需",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "740d91f0-622f-42b3-be2d-729c5f97c9d7_v11",
                  name: "街道",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "9752fa8c-67c7-4c6e-8730-f0967edb9e70_v11",
                  name: "街道分时",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "75fbe2c7-f74b-401b-8fa7-80eacee8deca_v11",
              name: "推荐点位",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "vtwo_menu_suggest_output_v11",
                  name: "电单推荐调出明细表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "vtwo_menu_suggest_input_v11",
                  name: "电单推荐调入明细表",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "80ca1185-0c73-4937-a5e9-a0a3c14a1169_v11",
              name: "停车点分析",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "4cecaf43-83fd-480b-9e11-6b8d225569d1_v11",
                  name: "停车点画像",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "5c9a88de-5872-4c8d-a9fc-5a19cc8a96eb_v11",
                  name: "停车点指标分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "49d14990-0bf0-4ad2-8810-f5db4107e359_v11",
                  name: "停车点运营指标分析",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "f5888a44-7a22-4ab0-bc44-d35e85c9f001_v11",
                  name: "违停订单分布地图",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "0571b51a-95d1-449a-abdf-61abea72d174_v11",
              name: "未骑行诊断",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "c7f50a85-849d-4544-98e3-4223213f4162_v11",
                  name: "健康车N日未骑行",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "31b77c43-28bf-4759-bd97-8d90de4a7a6e_v11",
                  name: "健康车7日未骑行",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
                {
                  id: null,
                  code: "3bb785cf-4cc4-42d7-9d57-2d965247ce58_v11",
                  name: "健康车7日未骑行_聚合地图",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
          ],
        },
        {
          id: null,
          code: "86ddaca7-dccc-4a82-b1de-c89a6878ae56_v11",
          name: "运营提效",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "d6a1ab36-70b6-47f8-9d0c-f2f448ec7a91_v11",
              name: "数据导出",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [
                {
                  id: null,
                  code: "e7d17c63-9e6b-45c3-ad25-14042f26d7a2_v11",
                  name: "电单车region数据导出",
                  cn: 0,
                  sn: 0,
                  tn: 0,
                  ext: { OP: "1", RT: "menu", IB: "0" },
                  items: [],
                },
              ],
            },
            {
              id: null,
              code: "4be3dc84-d49c-429d-bdf4-10b65cb83148_v11",
              name: "位置地图",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_order_map_v11",
              name: "订单地图",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
          ],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21860_v11",
      name: "我的收藏",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_myCollection_v11",
          name: "我的收藏",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21870_v11",
      name: "自助分析",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_reportlist_v11",
          name: "报表中心",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_tablelist_v11",
          name: "单图列表",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_CDSList_v11",
          name: "数据源列表",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_materializedView_v11",
          name: "物化视图",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21880_v11",
      name: "火龙果",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_22190_v11",
          name: "多维取数",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_22200_v11",
          name: "个人看板",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_22210_v11",
          name: "共享看板",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21890_v11",
      name: "高级分析",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_user_action_analysis_v11",
          name: "用户行为分析",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [
            {
              id: null,
              code: "vtwo_menu_25000_v11",
              name: "用户分群",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_25001_v11",
              name: "用户细查",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_25002_v11",
              name: "用户路径",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_25003_v11",
              name: "用户分层",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
            {
              id: null,
              code: "vtwo_menu_25004_v11",
              name: "用户报告",
              cn: 0,
              sn: 0,
              tn: 0,
              ext: { OP: "1", RT: "menu", IB: "0" },
              items: [],
            },
          ],
        },
        {
          id: null,
          code: "vtwo_menu_listEvent_1_v11",
          name: "事件分析",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_listEvent_2_v11",
          name: "漏斗分析",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_24000_v11",
      name: "数据治理门户",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_23620_v11",
          name: "数据监控",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
      ],
    },
    {
      id: null,
      code: "vtwo_menu_21900_v11",
      name: "配置模块",
      cn: 0,
      sn: 0,
      tn: 0,
      ext: { OP: "1", RT: "menu", IB: "0" },
      items: [
        {
          id: null,
          code: "vtwo_menu_mbkuseroauth_v11",
          name: "用户配置",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_mbkresourceoauth_v11",
          name: "资源配置",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_mbkroleoauth_v11",
          name: "角色配置",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_indicatorManagement_v11",
          name: "指标管理",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_infomessage_v11",
          name: "信息中心",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_22300_v11",
          name: "访问量报表",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_menu_22310_v11",
          name: "数据生产",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "menu", IB: "0" },
          items: [],
        },
        {
          id: null,
          code: "vtwo_page_shouquan",
          name: "主动授权",
          cn: 0,
          sn: 0,
          tn: 0,
          ext: { OP: "1", RT: "page", IB: "0" },
          items: [],
        },
      ],
    },
  ],
};
